name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-eslint:
    name: Lint
    runs-on: windows-latest
   
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      
      - name: Set npm shell
        run: npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Code Linting Check
        run: npm run lint:check